<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDesjbak\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDesjbak/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDesjbak.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDesjbak\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDesjbak\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Desjbak',
    'container.build_id' => '2318abf6',
    'container.build_time' => 1519406444,
));
